server:
  port: 7083

logging:
  file:
    path: ./log

spring:
  application:
    name: jraft

jraft:
  dataPath: f:\\temp\\server8083
  groupId: election_test
  serverId: 127.0.0.1:8083
  initConf: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083